[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.4"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"
